apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-env-configmap
data:
  DATA_SOURCE: "jdbc:mysql://192.168.1.20:3306/payment_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  DB_USERNAME: "root"
  DB_PASS: "Cmh771998@"

